blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from base_pages import views as base_pages_views

app_name = "blog"

urlpatterns = [
    path('', views.posts, name="posts"),
    path('<slug:slug>', views.categories, name="categories"),
    path('subcategories/<slug:slug>', views.sub_categories, name="subcategories"),
    path('post/<slug:slug>', views.detail, name="detail"),
    path('add_post/', views.add_post, name="add_post"),
    path('add_post2/', views.add_post2, name="add_post2"),
    path('update/<slug:slug>', views.update_post, name="update"),
    path('delete/<slug:slug>', views.delete_post, name="delete"),
    path('comment/<slug:slug>', views.add_comment, name="comment"),

]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('', views.jobs, name="jobs"),
    path('job/<slug:slug>', views.detail, name="detail"),
    path('add_job/', views.add_job, name="add_job"),
    path('update/<slug:slug>', views.update_job, name="update"),
    path('delete/<slug:slug>', views.delete_job, name="delete"),
    path('1', views.listing, name="listing"),

]

kolayinibul/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as post_views
from base_pages import views as base_pages_view
from user import views as user_pages_view
from job import views as job_views
from blog import views as blog_views
from job import views as job_views
from django.conf import settings
from django.conf.urls import url, handler400, handler500
from django.conf.urls.static import static
from base_pages.sitemaps import PostSitemap, StaticViewSitemap, JobAdvertisementSitemap, CategorySitemap, \
    SubcategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'posts': PostSitemap,
    'jobs': JobAdvertisementSitemap,
    'static': StaticViewSitemap,
    'category': CategorySitemap,
    'subcategory': SubcategorySitemap,
}

urlpatterns = [
    # admin App:
    path('admin/', admin.site.urls),

    # user App:
    path('user/', include("user.urls", namespace="user")),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),

    # oAuth Login:
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/password/$', user_pages_view.github_password, name='password'),

    # blog App:
    path('posts/', include("blog.urls", namespace="posts")),
    path('categories/', include("blog.urls", namespace="categories")),
    path('categories/<slug:slug>', blog_views.categories, name="categories"),

    # job App:
    path('jobs/', include("job.urls", namespace="jobs")),

    # base_pages App:
    path('', base_pages_view.index, name="index"),
    path('about_us/', base_pages_view.about, name="about_us"),
    path('dashboard/', base_pages_view.dashboard, name="dashboard"),
    path('my_posts/', base_pages_view.my_posts, name="my_posts"),
    path('my_jobs/', base_pages_view.my_jobs, name="my_jobs"),
    path('my_profile/', base_pages_view.my_profile, name="my_profile"),
    path('faq/', base_pages_view.faq, name="faq"),
    path('contact_us/', base_pages_view.contact_us, name="contact_us"),
    path('search/', base_pages_view.search_view, name="search_view"),
    path('privacy_page/', base_pages_view.privacy_page, name="privacy_page"),
    path('jobs/', base_pages_view.job_page_coming_soon, name="job_page_coming_soon"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', include("robots.urls", namespace="")),
    url(r'^robots\.txt', include('robots.urls')),

    # Advertorials
    path('ads.txt/', base_pages_view.ads, name="ads"),

    # 404 and 500 Error Pages
    path('404_test/', base_pages_view.handler404, name="404_test"),
    path('500_test/', base_pages_view.handler500, name="500_test"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('edit_profile/', views.update_profile, name="update_profile"),


]

blog/models.py
from django.db import models
from django.db import models
from django.db.models import F
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=50, verbose_name="Category Adı")
    slug = models.SlugField(max_length=55, blank=True, null=True)

    def save(self, *args, **kwargs):
        print(self.category_name)

        if not self.slug:
            self.slug = self.get_slug()
            print(self.slug)
        print(self.category_name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return "{category_name}".format(category_name=self.category_name)

    def get_slug(self):
        slug = self.category_name.replace("ı", "i")
        return slugify(slug)

    def get_absolute_url(self):
        return reverse('categories:categories', args=[str(self.slug)])


class SubCategory(models.Model):
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='subcategories')
    sub_category_name = models.CharField(max_length=50, verbose_name="Alt-Category Adı")
    slug = models.SlugField(max_length=55, blank=True, null=True)
    sub_category_image = models.FileField(upload_to='sub_category_images/', null=True, blank=True)

    def save(self, *args, **kwargs):
        print(self.sub_category_name)

        if not self.slug:
            self.slug = self.get_slug()
            print(self.slug)
        print(self.sub_category_name)
        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self):
        return "{sub_category_name}".format(sub_category_name=self.sub_category_name)

    def get_slug(self):
        slug = self.sub_category_name.replace("ı", "i")
        return slugify(slug)

    def get_absolute_url(self):
        return reverse('categories:subcategories', args=[str(self.slug)])


class Post(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    category = models.ForeignKey("Category", on_delete=models.CASCADE, verbose_name="Kategori Adı")
    sub_category = models.ForeignKey("SubCategory", on_delete=models.CASCADE, verbose_name="Alt Kategori Adı",
                                     related_name="sub_category")
    title = models.CharField(max_length=50, verbose_name="Post Başlığı")
    slug = models.SlugField(max_length=55, blank=True, null=True)
    description = RichTextField(max_length=100000, null=False, verbose_name="Açıklama")
    image = models.ImageField(upload_to='post_images/', null=True, blank=True,
                              default='')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_date = models.DateTimeField(blank=True, null=True, verbose_name="Updated Date")
    verified_date = models.DateTimeField(auto_now_add=True, verbose_name="Verified Date")
    sources = models.CharField(max_length=250, verbose_name="Kaynak", blank=True, null=True)

    STATUS_DRAFT = 1
    STATUS_PUBLISHED = 2
    STATUS_ARCHIVED = 3
    STATUS_DEACTIVATED = 4
    STATUS_WAITING_APPROVAL = 5
    STATUSES = (
        (STATUS_DRAFT, 'Taslak'),
        (STATUS_PUBLISHED, 'Yayında'),
        (STATUS_ARCHIVED, 'Arşivlendi'),
        (STATUS_DEACTIVATED, 'Kaldırıldı'),
        (STATUS_WAITING_APPROVAL, "Onay Bekliyor")
    )
    active_post = models.SmallIntegerField(choices=STATUSES, default=5)
    #  Page Header Content'de bir büyük iki küçük box'ta görünmesi için üç değer verelim.
    LOCATION_BIG = 1
    LOCATION_SMALL1 = 2
    LOCATION_SMALL2 = 3
    LOCATION_OTHER = 4
    LOCATION = (
        (LOCATION_BIG, 'Big Box'),
        (LOCATION_SMALL1, 'First Small Box'),
        (LOCATION_SMALL2, 'Second Small Box'),
        (LOCATION_OTHER, 'Other'),
    )
    page_header_content = models.SmallIntegerField(choices=LOCATION, default=4)
    tag = models.ManyToManyField(SubCategory, default=sub_category)

    def save(self, *args, **kwargs):
        print(self.title)

        if not self.slug:
            self.slug = self.get_slug()
            print(self.slug)
        print(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return "{title} - {pk}".format(pk=self.pk, title=self.title)

    def get_slug(self):
        slug = self.title.replace("ı", "i")
        slug += "-" + get_random_string(4)
        return slugify(slug)

    def get_absolute_url(self):
        return reverse('posts:detail', args=[str(self.slug)])

    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Post", related_name="comments")
    comment_author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yorum Sahibi")
    comment_content = models.CharField(max_length=1000, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['comment_date']

job/models.py
from django.db import models
from django.db.models import F
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from blog.models import Category, SubCategory


class JobAdvertisement(models.Model):
    employer = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="İşveren")
    company_name = models.CharField(max_length=50, verbose_name="Firma Adı", blank=True, null=True)
    email_adress = models.EmailField(blank=True, null=True)
    avg_salary = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True, verbose_name="Ortalama Maaş")
    category = models.ForeignKey('blog.Category', on_delete=models.CASCADE, verbose_name="Kategori Adı",
                                 related_name="job_category")
    sub_category = models.ForeignKey('blog.SubCategory', on_delete=models.CASCADE, verbose_name="Alt Kategori Adı",
                                     related_name="job_sub_category")
    title = models.CharField(max_length=50, verbose_name="Pozisyon")
    slug = models.SlugField(max_length=55, blank=True, null=True)
    description = RichTextField(max_length=100000, null=False, verbose_name="İş Açıklaması")
    company_logo = models.ImageField(upload_to='company_logos/', null=True, blank=True,
                                     default='')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    updated_date = models.DateTimeField(blank=True, null=True, verbose_name="Updated Date")
    verified_date = models.DateTimeField(auto_now_add=True, verbose_name="Verified Date")

    TYPE_COMPANY = 1
    TYPE_INDIVIDUAL = 2
    TYPES = (
        (TYPE_COMPANY, 'Firma'),
        (TYPE_INDIVIDUAL, 'Bireysel')
    )
    type = models.SmallIntegerField(choices=TYPES, verbose_name="İşveren Tipi")

    TERM_SHORT = 1
    TERM_LONG = 2
    TERM_ONE_TIME = 3
    TERM_INTERNSHIP = 4
    TERM_REMOTE = 5
    TERMS = (
        (TERM_SHORT, 'Kısa Dönem'),
        (TERM_LONG, 'Uzun Dönem'),
        (TERM_ONE_TIME, 'Tek Seferlik'),
        (TERM_INTERNSHIP, 'Staj'),
        (TERM_REMOTE, 'Remote')
    )
    term = models.SmallIntegerField(choices=TERMS, verbose_name="Dönem")

    STATUS_DRAFT = 1
    STATUS_PUBLISHED = 2
    STATUS_ARCHIVED = 3
    STATUS_DEACTIVATED = 4
    STATUS_WAITING_APPROVAL = 5
    STATUSES = (
        (STATUS_DRAFT, 'Taslak'),
        (STATUS_PUBLISHED, 'Yayında'),
        (STATUS_ARCHIVED, 'Arşivlendi'),
        (STATUS_DEACTIVATED, 'Kaldırıldı'),
        (STATUS_WAITING_APPROVAL, "Onay Bekliyor")
    )
    job_status = models.SmallIntegerField(choices=STATUSES, default=5)
    tag = models.ManyToManyField(SubCategory, default=sub_category)

    def save(self, *args, **kwargs):
        print(self.title)

        if not self.slug:
            self.slug = self.get_slug()
            print(self.slug)
        print(self.title)
        super(JobAdvertisement, self).save(*args, **kwargs)

    def __str__(self):
        return "{title} - {pk} - {company_name}".format(pk=self.pk, title=self.title, company_name=self.company_name)

    def get_slug(self):
        slug = self.title.replace("ı", "i")
        slug += "-" + get_random_string(4)
        return slugify(slug)

    def get_absolute_url(self):
        return reverse('jobs:detail', args=[str(self.slug)])

templates/profile_pages/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/profile_pages/edit_profile.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Profilini Güncelle - {{ block.super }}{% endblock %}



{% block body %}


    <section class="s-content" style="padding-top: 0px">
        <section id="styles" class="s-styles">
            <div class="row">
                <div class="col-full tab-full">
                    <div class="heading">
                        <h2>Profilini Güncelle</h2>
                    </div>
                    <hr>
                    <form method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.media }}
                        {{ form }}

                        <button type="submit" class="btn--primary full-width">Güncelle</button>
                        <hr>
                    </form>
                </div>
            </div>



        </section>
    </section>

{% endblock %}

templates/profile_pages/my_jobs.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}İş İlanlarım - {{ block.super }}{% endblock %}

{% block body %}

<section class="s-content" style="padding-top: 0px">
        <section id="styles" class="s-styles">
            <br>


            <div class="row add-bottom">
                <h3>Yayınladığım İş İlanlarım</h3>
                <div class="col-twelve">
                    <div class="table-responsive">

                        <table>
                            <thead>
                            <tr>

                                <th style="text-align: center">Pozisyon</th>
                                <th style="text-align: center">Firma Adı</th>
                                <th style="text-align: center">Kategori</th>
                                <th style="text-align: center">Alt Kategori</th>
                                <th style="text-align: center">İlan Tarihi</th>
                                <th style="text-align: center">Çalışma Türü</th>
                                <th style="text-align: center"></th>


                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}
                                <tr>

                                    <td><a href="{% url 'jobs:detail' slug=job.slug %}">{{ job.title }}</a></td>
                                    <td>{{ job.company_name }}</td>
                                    <td>{{ job.category }}</td>
                                    <td>{{ job.sub_category }}</td>
                                    <td>{{ job.created_date|date:"F d, Y"  }}</td>
                                    <td>{{ job.get_type_display }}</td>
                                    <td>{{ job.get_term_display }}</td>
                                <td><a class="btn btn-primary" href="{% url 'jobs:update' slug=job.slug %}">İlanı Düzenle</a></td>
                                {% if job.job_status == 2 %}
                                        <td><a href="{% url 'jobs:delete' slug=job.slug %}" class="btn btn-info">Yayından
                                            Kaldır</a>
                                            {% else %}
                                        <td>
                                        <a href="{% url 'jobs:delete' slug=job.slug %}" class="btn btn-info">Yayına
                                            Al</a>
                                    {% endif %}


                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>

                </div>

            </div> <!-- end row -->
        </section>
    </section>

{% endblock body %}

templates/profile_pages/my_posts.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Post Yazılarım - {{ block.super }}{% endblock %}

{% block body %}

<section class="s-content" style="padding-top: 0px">
        <section id="styles" class="s-styles">
            <br>


            <div class="row add-bottom">
                <h1>Yayınladığım Postlarım</h1>
                <div class="col-twelve">
                    <div class="table-responsive">

                        <table>
                            <thead>
                            <tr>
                                <th style="text-align: center">Başlık</th>
                                <th style="text-align: center">Kategori</th>
                                <th style="text-align: center">Alt Kategori</th>
                                <th style="text-align: center">Eklenme Tarihi</th>
                                <th style="text-align: center">Durum</th>
                                <th style="text-align: center">Okunma</th>
                                <th style="text-align: center">Beğenme</th>


                            </tr>
                            </thead>
                            <tbody>
                            {% for post in posts %}
                                <tr>
                                    <td><a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a></td>
                                    <td>{{ post.category }}</td>
                                    <td>{{ post.sub_category }}</td>
                                    <td>{{ post.created_date|date:"F d, Y"  }}</td>
                                    <td>{{ post.get_active_post_display }}</td>


                                    <td>0</td>
                                    <td>0</td>
                                    <td><a href="{% url 'posts:update' slug=post.slug %}"
                                           class="btn btn-info">Düzenle</a></td>
                                    {% if post.active_post == 2 %}
                                        <td><a href="{% url 'posts:delete' slug=post.slug %}" class="btn btn-info">Yayından
                                            Kaldır</a>
                                            {% else %}
                                        <td>
                                        <a href="{% url 'posts:delete' slug=post.slug %}" class="btn btn-info">Yayına
                                            Al</a>
                                    {% endif %}
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>

                </div>

            </div> <!-- end row -->

        </section>
    </section>

{% endblock body %}

templates/profile_pages/my_profile.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Profilim - {{ block.super }}{% endblock %}



{% block body %}


    <section class="s-content" style="padding-top: 0rem">
        <section id="styles" class="s-styles">
            <hr>
            <div class="container bootstrap snippet">
                <div class="row">

                    <div class="col-sm-3" style="border: #EFC702 dashed 2px; padding: 19px"><!--left col-->

                        <div class="text-center">

                            <h1 align="center" style="margin-top: 0rem">{{ profile_detail.user }}</h1>
                            <img src="{{ profile_detail.avatar.url }}" class="avatar img-circle img-thumbnail"
                                 alt="avatar" style="width: 150px;height: 150px">
                            <br>
                            <a class="btn btn-primary" href="{% url 'user:update_profile' %}">Profilini Güncelle</a>
                        </div>
                    <hr>
                        <div style="text-align: justify;word-wrap: break-spaces;width: 155px">

                            <p>{{ profile_detail.bio }}</p>
                        </div>
                        <hr>
                        <ul class="disc">
                            <li class="list-group-item text-right"><span
                                    class="pull-left"><strong>Postlar</strong></span>{{ user_posts.count }}</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong>İş İlanları</strong></span>{{ user_jobs.count }}
                            </li>
                            <li class="list-group-item text-right"><span
                                    class="pull-left"><strong>Takipçiler</strong></span> 0
                            </li>
                            <li class="list-group-item text-right"><span
                                    class="pull-left"><strong>Takip Ettikleri</strong></span> 0
                            </li>
                        </ul>
                        <div class="panel panel-default" align="center">
                            <hr>
                            <div class="panel-body">
                                {% if profile_detail.github_profile %}
                                    <a href="{{ profile_detail.github_profile }}" target="_blank"><img
                                            style="width: 24px"
                                            src="{% static 'icons/github.png' %}"
                                            alt=""></a>
                                {% else %}
                                {% endif %}
                                {% if profile_detail.linkedin_profile %}
                                    <a href="{{ profile_detail.linkedin_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/linkedin.png' %}" alt=""></a>
                                {% else %}
                                {% endif %}

                                {% if profile_detail.stack_overflow_profile %}
                                    <a href="{{ profile_detail.stack_overflow_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/stack-overflow.png' %}"
                                             alt=""></a>
                                {% else %}
                                {% endif %}

                                {% if profile_detail.twitter_profile %}
                                    <a href="{{ profile_detail.twitter_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/twitter.png' %}" alt=""></a>
                                {% else %}
                                {% endif %}

                                {% if profile_detail.instagram_profile %}
                                    <a href="{{ profile_detail.instagram_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/instagram.png' %}" alt=""></a>
                                {% else %}
                                {% endif %}

                                {% if profile_detail.skype_profile %}
                                    <a href="{{ profile_detail.skype_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/skype.png' %}" alt=""></a>
                                {% else %}
                                {% endif %}

                                {% if profile_detail.spotify_profile %}
                                    <a href="{{ profile_detail.spotify_profile }}" target="_blank">
                                        <img style="width: 24px" src="{% static 'icons/spotify.png' %}" alt=""></a>
                                {% else %}
                                {% endif %}
                            </div>
                            <hr>
                            {% if github_login %}
                                <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/"
                                                   target="_blank">{{ github_login.extra_data.login }}</a></p>
                                {% if can_disconnect %}
                                    <form method="post" action="{% url 'social:disconnect' 'github' %}">
                                        {% csrf_token %}
                                        <button class="btn--primary" type="submit">Disconnect f/ GitHub</button>
                                    </form>
                                {% else %}
                                    <button type="button" disabled>Disconnect from GitHub</button>
                                    <p style="color: red">You must <a href="{% url 'password' %}">define a password</a>
                                        for your account before disconnecting from Github.</p>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
                            {% endif %}
                        </div>

                    </div><!--/col-3-->
                    <div class="col-sm-9">
                        <div class="tab-content">
                            <div class="table-bordered">
                                <br><br><br>
                                <a href="{% url 'my_posts' %}"><h6>Yayınladığım Postlarım</h6></a>
                                <ul>
                                {% if user_posts %}
                                    {% for post in user_posts %}
                                        <li>
                                            <a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a>
                                        </li>
                                    {% endfor %}
                                {% else %}
                                    <li><a href="{% url 'posts:add_post' %}">Hiç postunuz yok. Hemen oluşturun!</a>
                                </li>
                                {% endif %}
                                </ul>
                            </div>
                            <div class="table-bordered">
                                <br><br><br>
                                <a href="{% url 'my_jobs' %}"><h6>Yayınladığım İş İlanlarım</h6></a>
                                <ul>
                                {% if user_jobs %}
                                    {% for job in user_jobs %}
                                        <li>
                                            <a href="{% url 'jobs:detail' slug=job.slug %}">{{ job.title }}</a>
                                        </li>
                                    {% endfor %}
                                {% else %}
                                <li>
                                    <a href="{% url 'jobs:add_job' %}">Hiç iş ilanınız yok. Hemen oluşturun!</a>
                                </li>
                                {% endif %}
                                </ul>
                            </div>


                        </div><!--/tab-pane-->
                    </div><!--/tab-content-->



                </div><!--/col-9-->
            </div><!--/row-->


        </section>
    </section>

{% endblock %}