blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from base_pages import views as base_pages_views

app_name = "blog"

urlpatterns = [
    path('', views.posts, name="posts"),
    path('<slug:slug>', views.categories, name="categories"),
    path('subcategories/<slug:slug>', views.sub_categories, name="subcategories"),
    path('post/<slug:slug>', views.detail, name="detail"),
    path('add_post/', views.add_post, name="add_post"),
    path('add_post2/', views.add_post2, name="add_post2"),
    path('update/<slug:slug>', views.update_post, name="update"),
    path('delete/<slug:slug>', views.delete_post, name="delete"),
    path('comment/<slug:slug>', views.add_comment, name="comment"),

]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('', views.jobs, name="jobs"),
    path('job/<slug:slug>', views.detail, name="detail"),
    path('add_job/', views.add_job, name="add_job"),
    path('update/<slug:slug>', views.update_job, name="update"),
    path('delete/<slug:slug>', views.delete_job, name="delete"),
    path('1', views.listing, name="listing"),

]

kolayinibul/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as post_views
from base_pages import views as base_pages_view
from user import views as user_pages_view
from job import views as job_views
from blog import views as blog_views
from job import views as job_views
from django.conf import settings
from django.conf.urls import url, handler400, handler500
from django.conf.urls.static import static
from base_pages.sitemaps import PostSitemap, StaticViewSitemap, JobAdvertisementSitemap, CategorySitemap, \
    SubcategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'posts': PostSitemap,
    'jobs': JobAdvertisementSitemap,
    'static': StaticViewSitemap,
    'category': CategorySitemap,
    'subcategory': SubcategorySitemap,
}

urlpatterns = [
    # admin App:
    path('admin/', admin.site.urls),

    # user App:
    path('user/', include("user.urls", namespace="user")),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),

    # oAuth Login:
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/password/$', user_pages_view.github_password, name='password'),

    # blog App:
    path('posts/', include("blog.urls", namespace="posts")),
    path('categories/', include("blog.urls", namespace="categories")),
    path('categories/<slug:slug>', blog_views.categories, name="categories"),

    # job App:
    path('jobs/', include("job.urls", namespace="jobs")),

    # base_pages App:
    path('', base_pages_view.index, name="index"),
    path('about_us/', base_pages_view.about, name="about_us"),
    path('dashboard/', base_pages_view.dashboard, name="dashboard"),
    path('my_posts/', base_pages_view.my_posts, name="my_posts"),
    path('my_jobs/', base_pages_view.my_jobs, name="my_jobs"),
    path('my_profile/', base_pages_view.my_profile, name="my_profile"),
    path('faq/', base_pages_view.faq, name="faq"),
    path('contact_us/', base_pages_view.contact_us, name="contact_us"),
    path('search/', base_pages_view.search_view, name="search_view"),
    path('privacy_page/', base_pages_view.privacy_page, name="privacy_page"),
    path('jobs/', base_pages_view.job_page_coming_soon, name="job_page_coming_soon"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', include("robots.urls", namespace="")),
    url(r'^robots\.txt', include('robots.urls')),

    # Advertorials
    path('ads.txt/', base_pages_view.ads, name="ads"),

    # 404 and 500 Error Pages
    path('404_test/', base_pages_view.handler404, name="404_test"),
    path('500_test/', base_pages_view.handler500, name="500_test"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('edit_profile/', views.update_profile, name="update_profile"),


]

templates/base/components/advert_left_right.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/components/breadcrumb.html
<div class="bcAds" align="center" style="background-color: #F2F2F2" id="bcAds">
<!-- ReklamStore kodu basla -  sidebar -->
<script type="text/javascript">
    var reklamstore_region_id = 546492;
</script>
<script type="text/javascript" src="//adserver.reklamstore.com/reklamstore.js"></script>
<!-- ReklamStore kodu bitti - sidebar-->

    </div>

templates/base/components/footer.html
{% load static %}


<!-- s-footer
================================================== -->
<footer class="s-footer">

    <div class="s-footer__main">
        <div class="row">

            <div class="col-two md-four mob-full s-footer__sitelinks">

                <h4>Hızlı Linkler</h4>

                <ul class="s-footer__linklist">
                    <li><a href="{% url 'index' %}">Anasayfa</a></li>
                    <li><a href="{% url 'index' %}">Kategoriler</a></li>
                    <li><a href="{% url 'job_page_coming_soon' %}">İş İlanları</a></li>
                    <li><a href="{% url 'about_us' %}">Biz Kimiz?</a></li>
                    <li><a href="{% url 'contact_us' %}">İletişim</a></li>
                    <li><a href="{% url 'privacy_page' %}">Gizlilik Politikamız</a></li>


                </ul>

            </div> <!-- end s-footer__sitelinks -->


            <div class="col-two md-four mob-full s-footer__social">

                <h4>Sosyal Medya</h4>

                <ul class="s-footer__linklist">
                    <li><a target="_blank" href="https://github.com/mindlabcore">GitHub</a></li>
                    <li><a target="_blank" href="https://www.instagram.com/kolayinibul">Instagram</a></li>
                    <li><a target="_blank" href="https://twitter.com/kolayinibul">Twitter</a></li>
                    <li><a target="_blank" href="https://www.facebook.com/kolayinibul/">Facebook</a></li>
                    <!--<li><a href="#0">LinkedIn</a></li> -->
                </ul>

            </div> <!-- end s-footer__social -->

            <div class="col-five md-full end s-footer__subscribe">

                <h4>E-Posta Aboneliği</h4>

                <p>Şimdilik e-posta aboneliğimiz yok, buraya e-postanızı yazsanız bile hiçbir şey yapmayacağız SÖZ!.
                    Çünkü neden yapalım?</p>

                <div class="subscribe-form">
                    <form id="mc-form" class="group" novalidate="true">

                        <input type="email" value="" name="EMAIL" class="email" id="mc-email"
                               placeholder="E-Posta Adresi" required="">

                        <input type="submit" name="subscribe" value="Gönder">

                        <label for="mc-email" class="subscribe-message"></label>

                    </form>
                </div>

            </div> <!-- end s-footer__subscribe -->

        </div>
    </div> <!-- end s-footer__main -->

    <div class="s-footer__bottom">
        <div class="row">
            <div class="col-full">
                <div class="s-footer__copyright">
                    <span>© Copyright Kolayını Bul 2018</span><span>Founded by Mind Lab Co. 2018</span>

                    <span>Site Template by <a href="https://colorlib.com/">Colorlib</a></span>
                    <span>Coded with love by <a href="https://www.python.org/" target="_blank">Python 3.6</a> &nbsp<i
                            class="fas fa-heart"></i></span>
                    <span> <div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a
                            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a
                            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0"
                            target="_blank">CC 3.0
        BY</a></div></span>

                </div>

                <div class="go-top">
                    <a class="smoothscroll" title="Back to Top" href="#top"></a>
                </div>
            </div>
        </div>
    </div> <!-- end s-footer__bottom -->

</footer> <!-- end s-footer -->

templates/base/components/head.html
{% load static %}

<!--- basic page needs
    ================================================== -->
<meta charset="utf-8">
<meta name="title" content="Kolayını Bul">
<meta name="description" content="İnternet bir uzay boşluğu. O kadar çok bilgiye sahibiz ki hiçbir şeye ulaşamıyoruz. Bilgiye ulaşmak için harcadığımız zaman ulaştığımızda elde edeceğimiz faydadan daha faydalı. İşte tam burada yardımına biz koşuyoruz. Çok aramış insanların çok arayan insanlara yaptığı bir iyilik bu. Keyfine bak!">
<meta name="keywords" content="kolayı, kolay yolu, kolayını bul, kolay, bul, kolayca, basit, yazılım, kolaylık">
<meta name="robots" content="index, follow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="language" content="Turkish">
<meta name="revisit-after" content="3 days">
<meta name=”owner” content=”Mind Lab Co.” />
<meta name=”copyright” content=”(c) 2018” />

<!-- mobile specific metas
================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<!-- favicons
================================================== -->
<link rel="shortcut icon" href="{% static 'logo/KB.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'logo/KB.png' %}" type="image/x-icon">

<!-- Bootstrap4
==================================================
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
        crossorigin="anonymous"></script>
-->

<!-- Google Analytics -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-136767140-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-136767140-1');
</script>

<!-- Google Adsense -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1595289518925274",
    enable_page_level_ads: true
  });
</script>

<!--ExoClick-->
<meta name="exoclick-site-verification" content="4dff03ee293df78b2f378e3e4d3aeb36">

templates/base/components/navbar.html
{% load static %}

<body id="top">

<!-- pageheader
================================================== -->
<section class="s-pageheader s-pageheader--home">

    <header class="header">
        <div class="header__content row">

            <div class="header__logo">
                <a class="logo" href="{% url "index" %}">
                    <img class="masaustuLogo" style="width: 120px; height: 120px"
                         src="{% static 'logo/1781596764_b4fdb39e-54f8-49cd-b7db-7fe8b753a9f5 (1).png' %}"
                         alt="Homepage">

                    <img class="mobileLogo" style="width: 120px; height: 50px"
                         src="{% static 'logo/MobileLogo2.png' %}"
                         alt="Homepage">

                </a>
            </div> <!-- end header__logo -->

            <ul class="header__social">

                <li>
                    <a href="https://www.facebook.com/kolayinibul/" target="_blank"><i
                            class="fab fa-facebook-f"></i></a>
                </li>
                <li>
                    <a href="https://twitter.com/kolayinibul" target="_blank"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                    <a href="https://www.instagram.com/kolayinibul" target="_blank"><i class="fab fa-instagram"></i></a>
                </li>

                <li>
                    <a href="https://github.com/mindlabcore" target="_blank"><i class="fab fa-github"></i></a>
                </li>

            </ul> <!-- end header__social -->

            <a class="header__search-trigger" href="#0"></a>

            <div class="header__search">

                <form role="search" method="get" class="header__search-form" action="{% url 'search_view' %}">
                    <label>
                        <span class="hide-content">Ne arıyorsun?</span><br>
                        <input type="search" class="search-field" placeholder="Bir şeyler yaz!" value="" name="s"
                               title="Search for:" autocomplete="on" id="search_def">
                    </label>
                    <input type="submit" class="search-submit" value="Search">
                </form>

                <a href="#0" title="Close Search" class="header__overlay-close">Close</a>

            </div>  <!-- end header__search -->


            <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

            <nav class="header__nav-wrap">

                <h2 class="header__nav-heading h6">Site Navigation</h2>

                <ul class="header__nav">
                    <li class="has-children">
                        <a href="#0" title="">Kategoriler</a>
                        <ul class="sub-menu">
                            {% for category in categories %}
                                <li><a class=""
                                       href="{% url 'categories' slug=category.slug %}">{{ category.category_name }}</a>


                                    <ul class="sub-menu">

                                        {% for sub_category in category.subcategories.all %}
                                            <a class="" href="{% url 'categories:subcategories' slug=sub_category.slug %}">
                                                {{ sub_category }}
                                            </a>
                                        {% endfor %}

                                    </ul>


                                </li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li class="has-children">
                        <a href="#0" title="">İş İlanları</a>
                        <ul class="sub-menu">
                    <li><a href="{% url 'job:jobs' %}" title="">Açık İlanlar</a></li>
                            <li><a href="{% url 'job:add_job' %}" title="">İlan Ver</a></li>
                        </ul>
                    </li>


                    <li><a href="{% url 'about_us' %}" title="">Biz Kimiz?</a></li>
                    <li><a href="{% url 'contact_us' %}" title="">İletişim</a></li>

                    {% if request.user.is_authenticated %}
                        <li class="has-children">
                            <a href="#0" title="">{{ request.user.username }}</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'my_profile' %}">Profil Sayfam</a></li>
                                <li><a href="{% url 'my_posts' %}">Postlarım</a></li>
                                <li><a href="{% url 'my_jobs' %}">İş İlanlarım</a></li>
                                <li><a href="{% url 'user:change_password' %}">Şifremi Değiştir</a></li>
                                <li><a href="{% url 'user:logout' %}">Çıkış Yap</a></li>
                            </ul>
                        </li>

                    {% else %}
                        <li><a href="{% url 'user:login' %}" title="">Giriş Yap</a></li>
                        <li><a href="{% url 'user:sign_up' %}" title="">Kayıt Ol</a></li>



                    {% endif %}
                    <li>
                        <a href="{% url 'posts:add_post' %}" class="writeButton"
                           style="color:#000000; text-align: center">Kolayını
                            Yaz</a>
                    </li>
                </ul>
                <!-- end header__nav -->

                <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end header__nav-wrap -->

        </div>
        <!-- header-content -->
    </header> <!-- header -->
    <hr>

    {% url 'index' as current_url %}
    {% if request.get_full_path == current_url %}
        {% include 'base/components/page_header_content.html' %}
    {% else %}
    {% endif %}

</section>

templates/base/components/page_header_content.html
{% load static %}

<div class="pageheader-content row">
    <div class="col-full">

        <!-- start featured__big -->
        <div class="featured">

            <div class="featured__column featured__column--big">
                <div class="entry"
                     style="background-image:url('{% static 'images/thumbs/featured/featured_1-min.jpg' %}');">
                    {% if big_box %}
                        <div class="entry__content">

                        <span class="entry__category">
                            <a href="{% url 'categories:subcategories' slug=big_box.sub_category.slug %}">{{ big_box.sub_category }}</a></span>

                            <h1><a href="{% url 'posts:detail' slug=big_box.slug %}" title="">{{ big_box.title }}</a>
                            </h1>

                            <div class="entry__info">
                                <a href="{% url 'user:profile' slug=big_box.author %}" class="entry__profile-pic">
                                    <img class="avatar" src="{{ big_box.author.profile.avatar.url }}" alt="">
                                </a>

                                <ul class="entry__meta">
                                    <li>
                                        <a href="{% url 'user:profile' slug=big_box.author.profile %}">{{ big_box.author }}</a>
                                    </li>
                                    <li>{{ big_box.created_date|date:"F d, Y" }}</li>
                                </ul>
                            </div>
                        </div> <!-- end entry__content -->
                    {% else %}

                    {% endif %}
                </div> <!-- end entry -->
            </div> <!-- end featured__big -->

            <!-- start featured__second_box -->

            <div class="featured__column featured__column--small">
                <div class="entry"
                     style="background-image:url('{% static 'images/thumbs/featured/featured_2-min.jpg' %}');">
                    <div class="entry__content">
                        {% if second_box %}
                            <span class="entry__category"><a
                                    href="{% url 'categories:subcategories' slug=second_box.sub_category.slug %}">{{ second_box.sub_category }}</a></span>
                            <h1><a href="{% url 'posts:detail' slug=second_box.slug %}"
                                   title="">{{ second_box.title }}</a>
                            </h1>

                            <div class="entry__info">


                                <ul class="entry__meta">
                                    <li>
                                        <a href="{% url 'user:profile' slug=second_box.author %}">
                                            {{ second_box.author }}</a>
                                    </li>
                                    <li>{{ second_box.created_date|date:"F d, Y" }}</li>
                                </ul>
                            </div>
                        {% else %}

                        {% endif %}
                    </div>

                    <!-- end entry__content -->

                </div>
                <!-- end entry -->
                <!-- end featured__second_box -->

                <!-- start featured__third_box -->

                {% if third_box %}
                    <div class="entry"
                         style="background-image:url('{% static 'images/thumbs/featured/featured_3-min.jpg' %}');">
                        <div class="entry__content">
                            <span class="entry__category"><a style="background-color: #aa6600"
                                                             href="{% url 'categories:subcategories' slug=third_box.sub_category.slug %}">
                                {{ third_box.sub_category }}
                            </a>
                            </span>
                            <h1><a href="{% url 'posts:detail' slug=third_box.slug %}"
                                   title="">{{ third_box.title }}</a>
                            </h1>
                            <div class="entry__info">
                                <ul class="entry__meta">
                                    <li>
                                        <a href="{% url 'user:profile' slug=third_box.author %}">{{ third_box.author }}</a>
                                    </li>
                                    <li>{{ third_box.created_date|date:"F d, Y" }}</li>
                                </ul>
                            </div>

                        </div> <!-- end entry__content -->
                    </div> <!-- end entry -->
                {% else %}
                    <!--advertorial-->
                    <div class="entry" style="background-color: transparent">
                        <div class="entry__content">
                            <div style="text-align: center;width: content-box">
                                <script type="text/javascript">
                                    var ad_idzone = "3358958",
                                        ad_width = "300",
                                        ad_height = "250"
                                </script>
                                <script type="text/javascript" src="https://ads.exdynsrv.com/ads.js"></script>
                                <noscript>
                                    <iframe src="https://syndication.exdynsrv.com/ads-iframe-display.php?idzone=3358958&output=noscript&type=300x250"
                                            width="300" height="250" scrolling="no" marginwidth="0" marginheight="0"
                                            frameborder="0"></iframe>
                                </noscript>
                            </div>
                        </div> <!-- end entry__content -->
                    </div> <!-- end entry -->
                    <!-- Advertorial end -->

                {% endif %}

            </div> <!-- end featured -->
        </div> <!-- end featured__third_box -->


    </div> <!-- end col-full -->
</div> <!-- end pageheader-content row -->

templates/base/components/preloader.html
{% load static %}

<!-- preloader
================================================== -->
<div id="preloader">
    <div id="loader">
        <div class="line-scale">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>

templates/base/components/s-extra-footer-top.html
{% load static %}
{% load my_filters %}

<!-- s-extra
================================================== -->
<section class="s-extra">

    <div class="row top">

        <div class="col-eight md-six tab-full popular">
            <h3>Popüler Post'lar</h3>

            <div class="block-1-2 block-m-full popular__posts">
                {% for post in footer_post|slice:":6" %}
                    <article class="col-block popular__post">
                        <a href="#0" class="popular__thumb">
                            <img src="{{ post.sub_category.sub_category_image.url }}" alt="">
                        </a>
                        <h5><a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title|safe|upfirstletter }}</a></h5>
                        <section class="popular__meta">
                            <span class="popular__author"><span>By</span> <a href="{% url 'user:profile' slug=post.author %}">{{ post.author }}</a></span>
                            <span class="popular__date"><span>on</span> <time
                                    datetime="2017-12-19">{{ post.created_date|date:"F d, Y" }}</time></span>
                        </section>
                    </article>
                {% endfor %}
            </div> <!-- end popular_posts -->
        </div> <!-- end popular -->

        <div class="col-four md-six tab-full about">
            <h3>Biz Kimiz?</h3>

            <p>
                İnternet bir uzay boşluğu. O kadar çok bilgiye sahibiz ki hiçbir şeye ulaşamıyoruz. Bilgiye ulaşmak için
                harcadığımız zaman ulaştığımızda elde edeceğimiz faydadan daha faydalı. İşte tam burada
                yardımına biz koşuyoruz. Çok aramış insanların çok arayan insanlara yaptığı bir iyilik bu. Keyfine bak!
            </p>

            <ul class="about__social">
                <li>
                    <a href="https://www.facebook.com/kolayinibul/" target="_blank"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li>
                    <a href="https://twitter.com/kolayinibul" target="_blank"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                    <a href="https://www.instagram.com/kolayinibul" target="_blank"><i class="fab fa-instagram"></i></a>
                </li>

                <li>
                    <a href="https://github.com/mindlabcore" target="_blank"><i class="fab fa-github"></i></a>
                </li>
            </ul> <!-- end header__social -->
        </div> <!-- end about -->

    </div> <!-- end row -->


</section> <!-- end s-extra -->

templates/base/components/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/modernizr.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/pace.min.js' %}"></script>

<!--CKEDITOR Code Snippet -->
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
<link rel="stylesheet"
      href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.15.6/build/styles/default.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.15.6/build/highlight.min.js"></script>
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="/static/base/js/main.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<!--FontAwesome.css-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">