job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('', views.jobs, name="jobs"),
    path('job/<slug:slug>', views.detail, name="detail"),
    path('add_job/', views.add_job, name="add_job"),
    path('update/<slug:slug>', views.update_job, name="update"),
    path('delete/<slug:slug>', views.delete_job, name="delete"),
    path('1', views.listing, name="listing"),

]

kolayinibul/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as post_views
from base_pages import views as base_pages_view
from user import views as user_pages_view
from job import views as job_views
from blog import views as blog_views
from job import views as job_views
from django.conf import settings
from django.conf.urls import url, handler400, handler500
from django.conf.urls.static import static
from base_pages.sitemaps import PostSitemap, StaticViewSitemap, JobAdvertisementSitemap, CategorySitemap, \
    SubcategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'posts': PostSitemap,
    'jobs': JobAdvertisementSitemap,
    'static': StaticViewSitemap,
    'category': CategorySitemap,
    'subcategory': SubcategorySitemap,
}

urlpatterns = [
    # admin App:
    path('admin/', admin.site.urls),

    # user App:
    path('user/', include("user.urls", namespace="user")),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),

    # oAuth Login:
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/password/$', user_pages_view.github_password, name='password'),

    # blog App:
    path('posts/', include("blog.urls", namespace="posts")),
    path('categories/', include("blog.urls", namespace="categories")),
    path('categories/<slug:slug>', blog_views.categories, name="categories"),

    # job App:
    path('jobs/', include("job.urls", namespace="jobs")),

    # base_pages App:
    path('', base_pages_view.index, name="index"),
    path('about_us/', base_pages_view.about, name="about_us"),
    path('dashboard/', base_pages_view.dashboard, name="dashboard"),
    path('my_posts/', base_pages_view.my_posts, name="my_posts"),
    path('my_jobs/', base_pages_view.my_jobs, name="my_jobs"),
    path('my_profile/', base_pages_view.my_profile, name="my_profile"),
    path('faq/', base_pages_view.faq, name="faq"),
    path('contact_us/', base_pages_view.contact_us, name="contact_us"),
    path('search/', base_pages_view.search_view, name="search_view"),
    path('privacy_page/', base_pages_view.privacy_page, name="privacy_page"),
    path('jobs/', base_pages_view.job_page_coming_soon, name="job_page_coming_soon"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', include("robots.urls", namespace="")),
    url(r'^robots\.txt', include('robots.urls')),

    # Advertorials
    path('ads.txt/', base_pages_view.ads, name="ads"),

    # 404 and 500 Error Pages
    path('404_test/', base_pages_view.handler404, name="404_test"),
    path('500_test/', base_pages_view.handler500, name="500_test"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('edit_profile/', views.update_profile, name="update_profile"),


]

templates/help_pages/about_us.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Biz Kimiz? - {{ block.super }}{% endblock %}


{% block body %}
    <section class="s-content s-content--narrow">
        <hr>
        <br>

        <div class="row" style="border: #EFC702 dashed 2px;padding: 12px">

            <div class="col-twelve tab-full">
                <div class="row narrow section-intro add-bottom text-center">
                <h1  style="margin-bottom:-3rem">
                    Bizim Hakkımızda Daha Çok Şey!
                </h1></div>

            <div class="col-full s-content__main">
<div class="row narrow section-intro add-bottom text-center">
                <p class="lead">İnternet bir uzay boşluğu. O kadar çok bilgiye sahibiz ki hiçbir şeye ulaşamıyoruz.
                    Bilgiye ulaşmak için harcadığımız zaman ulaştığımızda elde edeceğimiz faydadan daha faydalı. İşte
                    tam burada yardımına biz koşuyoruz. Çok aramış insanların çok arayan insanlara yaptığı bir iyilik
                    bu. Keyfine bak!</p>
</div>


            </div>
                <div class="row block-1-2 block-tab-full">
                    <div class="col-block">
                        <h3 class="quarter-top-margin">Biz Kimiz?</h3>
                        <p class="drop-cap">Biz kimsesizlerin kimi, sessiz yığınların sesi değiliz. Biz ormanda kaybolduğunda karşına
                            çıkan pusulayız. Biz bildikleriyle yetinmeyenleriz. Bilmenin tamamlanan değil süren bir şey
                            olduğunu düşünenlerdeniz. 7 kıtada 7 dil konuşanların otobüste akbil sormaya utananlara el
                            uzattığı bir dünyada yaşamak istiyoruz.</p>
                    </div>

                    <div class="col-block">
                        <h3 class="quarter-top-margin">Misyonumuz ne?</h3>
                        <p class="drop-cap">
                            Bildiklerimizi paylaşırız. Paylaşanları buluştururuz. Buluşanları kaynaştırırız. Amacımız
                            her bireyi en doğru bilgiye en kısa yoldan ulaştırmak. Bunu yaparken bile öğretmek. Şarkı
                            dinlemekten sıkılmayan ama şarkı yazmayı da denemedim demeyen bireyleri bir araya getirmek
                            istiyoruz.
                        </p>
                    </div>

                    <div class="col-block">
                        <h3 class="quarter-top-margin">Vizyonumuz ne?</h3>
                        <p class="drop-cap">Toplumsal kalıplarından çıkamayan, diretmelere karşı koyamayan insanların kaçış bileti olmak,
                            önyargıları dozerle yıkmak, doğru bilgiye herkesin ulaşabilmesini sağlamak. Elden ele
                            yayalım lütfen!</p>
                    </div>

                    <div class="col-block">
                        <h3 class="quarter-top-margin">Değerlerimiz neler?</h3>
                        <p class="drop-cap">Eşitsizliğin her türünü karşı olmak! Bilginin bile. Mesele şu ki; yorgun hayatlar
                            yaşıyoruz. Bizlere bir nimet gibi sunulan kişiliklerimizin dışına çıkıp diğerlerinin
                            bildiklerini deneyimlemek istiyoruz. Bu yüzden en kıymetli değerimiz bilgiyi toplumun her
                            sınıfına kolayca ulaştırmak.</p>

                        <blockquote>
                            <p>And those who where seen dancing were thought to be insane by those who could not hear the music.</p>
                            <cite>Friederich Nietzsche</cite>
                        </blockquote>
                    </div>

                </div>


            </div> <!-- end s-content__main -->

        </div> <!-- end row -->

    </section> <!-- s-content -->

{% endblock %}

templates/help_pages/contact_us.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}İletişim - {{ block.super }}{% endblock %}


{% block body %}

    <section class="s-content s-content--narrow">
        <br> <br>

        <div class="row" style="border: #EFC702 dashed 2px;padding: 12px">

            <div class="s-content__header col-full">
                <h1 class="s-content__header-title">
                    Bize Ulaşmaktan Çekinme
                </h1>
            </div> <!-- end s-content__header -->

            <div class="col-full s-content__main">
                <div class="row">
                    <div class="col-six tab-full">
                        <h3>Neredeyiz?</h3>

                        <p>
                            Westbahnhof, <br>
                            BahnhofCity Wien West,<br>
                            Europaplatz 2/1/2, 1150 <br>
                            Vienna
                        </p>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1853.6057591585982!2d16.336636688686!3d48.196533126531484!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x476d07f54746e563%3A0x7a8c58b4cab4af55!2sRegus+-+Vienna+Westbahnhof!5e0!3m2!1str!2str!4v1555444195539!5m2!1str!2str"
                                width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

                    </div>

                    <div class="col-six tab-full">
                        <h3>İletişim Bilgileri</h3>

                        <p>iletisim@kolayinibul.com<br>

                        </p>

                    </div>
                </div> <!-- end row -->
                <hr>
                <h2>Bir sorun mu var? Hemen söyle!</h2>

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-actions" style="text-align: center">
                        <button type="submit">Gönder</button>
                    </div>
                </form>


            </div> <!-- end s-content__main -->

        </div> <!-- end row -->

    </section> <!-- s-content -->


{% endblock %}

templates/help_pages/faq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/help_pages/privacy_page.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Gizlilik Politikamız - {{ block.super }}{% endblock %}


{% block body %}

    <section class="s-content s-content--narrow">
        <br> <br>

        <div class="row" style="border: #EFC702 dashed 2px;padding: 12px">

            <div class="s-content__header col-full">
                <h1 class="s-content__header-title">
                    Gizlilik Politikamız
                </h1>
            </div> <!-- end s-content__header -->

            <div class="col-full s-content__main">
                <div class="row">

                        kolayinibul.com sitesi olarak kişisel gizlilik haklarınıza saygı duyuyor ve sitemizde geçirdiğiniz
                        süre zarfında bunu sağlamak için çaba sarfediyoruz. Kişisel bilgilerinizin güvenliği ile ilgili
                        açıklamalar aşağıda açıklanmış ve bilginize sunulmuştur.

                        <h3>KAYIT DOSYALARI</h3>
                        Birçok standard web sunucusunda olduğu gibi kolayinibul.com‘da istatistiksel amaçlı log dosyaları
                        kaydı tutmaktadır. Bu dosyalar; ip adresiniz, internet servis sağlayıcınız, tarayıcınızın
                        özellikleri, işletim sisteminiz ve siteye giriş-çıkış sayfalarınız gibi standard bilgileri
                        içermektedir. Log dosyaları kesinlikle istatistiksel amaçlar dışında kullanılmamakta ve
                        mahremiyetinizi ihlal etmemektedir.Ip adresiniz ve diğer bilgiler, şahsi bilgileriniz ile
                        ilişkilendirilmemektedir.

                        <h3>REKLAMLAR</h3>
                        Sitemizde dışarıdan şirketlerin reklamlarını yayınlamaktayız (Google, v.s.). Bu reklamlar çerez
                        (cookıes) içerebilir ve bu sirketler tarafından çerez bilgileri toplanabilir ve bizim bu bilgiye
                        ulaşmamız mümkün değildir. Biz Google Adsense, vb. şirketler ile çalışmaktayız lütfen onların
                        ilgili sayfalarından gizlilik sözleşmelerini okuyunuz.

                        <h3>ÇEREZLER (COOKİES)</h3>
                        “Cookie – Çerez” kelimesi web sayfası sunucusunun sizin bilgisayarınızın hard diskine
                        yerleştirdiği ufak bir text dosyasını tanımlamak için kullanılmaktadır. Sitemizin bazı
                        bölümlerinde kullanıcı kolaylığı sağlamak için çerez kullanılıyor olabilir. Ayrıca sitede mevcut
                        bulunan reklamlar aracılığıyla, reklam verilerinin toplanması için cookie ve web beacon
                        kullanılıyor olabilir. Bu tamamen sizin izninizle gerçekleşiyor olup, isteğiniz dahilinde
                        internet tarayıcınızın ayarlarını değiştirerek bunu engellemeniz mümkündür.

                        <h3>DIŞ BAĞLANTILAR</h3>
                        kolayinibul.com sitesi, sayfalarından farklı internet adreslerine bağlantı vermektedir. kolayinibul.com
                        link verdiği, banner tanıtımını yaptığı sitelerin içeriklerinden veya gizlilik prensiplerinden
                        sorumlu değildir. Burada bahsedilen bağlantı verme işlemi, hukuki olarak “atıfta bulunma” olarak
                        değerlendirilmektedir.

                        <h3>İLETİŞİM</h3>
                        kolayinibul.com sitesinde uygulanan gizlilik politikası ile ilgili; her türlü soru, görüş ve
                        düşüncelerinizi bize iletisim@kolayinibul.com adresinden iletebilirsiniz.



                </div> <!-- end s-content__main -->

            </div> <!-- end row -->
        </div>
    </section> <!-- s-content -->


{% endblock %}

templates/help_pages/search.html
{% extends "base/layout.html" %}
{% load static %}
{% block title %}Arama - {{ block.super }}{% endblock %}

{% block body %}

    <section class="s-content">

        <div class="row masonry-wrap">
            <div class="masonry">
                <div class="grid-sizer"></div>
                {% for post in searching_posts %}
                    <article class="masonry__brick entry format-standard" data-aos="fade-up">

                        <div class="entry__thumb">
                            <a href="{% url 'posts:detail' slug=post.slug %}" class="entry__thumb-link">
                                <img src="images/thumbs/masonry/tulips-400.jpg"
                                     srcset="images/thumbs/masonry/tulips-400.jpg 1x, images/thumbs/masonry/tulips-800.jpg 2x"
                                     alt="">
                            </a>
                        </div>

                        <div class="entry__text">
                            <div class="entry__header">




                                <div class="entry__date" style="text-align: right">
                                    <a href="{% url 'posts:detail' slug=post.slug %}">{{ post.created_date }}</a>

                                </div>
                                <h1 class="entry__title"><a
                                        href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a>
                                </h1>

                            </div>

                            <div class="entry__excerpt">
                                <p>
                                    {{ post.description|striptags|truncatewords:28|safe }}
                                </p>
                            </div>


                            <div class="entry__content">
                                <a href="{% url 'index' %}" class="entry__profile-pic">
                                    <img class="avatar" src="{{ post.author.profile.avatar.url }}" alt="">
                                </a>

                                <div class="entry__date">
                                    <a href="{% url 'user:profile' slug=post.author %}">&nbsp{{ post.author }}</a>

                                </div>
                                <br>


                                <div class="entry__meta">
                            <span class="entry__meta-links">
                                {% for tag in post.tag.all|slice:":3" %}
                                    <a href="{% url 'posts:categories' slug=post.category.slug %}">
                                {{ tag }}
                                </a>
                                {% endfor %}
                            </span>
                                </div>

                            </div>
                        </div>

                    </article> <!-- end article -->
                {% endfor %}

            </div> <!-- end masonry -->
        </div> <!-- end masonry-wrap -->



    </section> <!-- s-content -->

{% endblock body %}