blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from base_pages import views as base_pages_views

app_name = "blog"

urlpatterns = [
    path('', views.posts, name="posts"),
    path('<slug:slug>', views.categories, name="categories"),
    path('subcategories/<slug:slug>', views.sub_categories, name="subcategories"),
    path('post/<slug:slug>', views.detail, name="detail"),
    path('add_post/', views.add_post, name="add_post"),
    path('add_post2/', views.add_post2, name="add_post2"),
    path('update/<slug:slug>', views.update_post, name="update"),
    path('delete/<slug:slug>', views.delete_post, name="delete"),
    path('comment/<slug:slug>', views.add_comment, name="comment"),

]

job/urls.py
from django.urls import path
from . import views

app_name = "job"

urlpatterns = [
    path('', views.jobs, name="jobs"),
    path('job/<slug:slug>', views.detail, name="detail"),
    path('add_job/', views.add_job, name="add_job"),
    path('update/<slug:slug>', views.update_job, name="update"),
    path('delete/<slug:slug>', views.delete_job, name="delete"),
    path('1', views.listing, name="listing"),

]

kolayinibul/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as post_views
from base_pages import views as base_pages_view
from user import views as user_pages_view
from job import views as job_views
from blog import views as blog_views
from job import views as job_views
from django.conf import settings
from django.conf.urls import url, handler400, handler500
from django.conf.urls.static import static
from base_pages.sitemaps import PostSitemap, StaticViewSitemap, JobAdvertisementSitemap, CategorySitemap, \
    SubcategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'posts': PostSitemap,
    'jobs': JobAdvertisementSitemap,
    'static': StaticViewSitemap,
    'category': CategorySitemap,
    'subcategory': SubcategorySitemap,
}

urlpatterns = [
    # admin App:
    path('admin/', admin.site.urls),

    # user App:
    path('user/', include("user.urls", namespace="user")),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),

    # oAuth Login:
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/password/$', user_pages_view.github_password, name='password'),

    # blog App:
    path('posts/', include("blog.urls", namespace="posts")),
    path('categories/', include("blog.urls", namespace="categories")),
    path('categories/<slug:slug>', blog_views.categories, name="categories"),

    # job App:
    path('jobs/', include("job.urls", namespace="jobs")),

    # base_pages App:
    path('', base_pages_view.index, name="index"),
    path('about_us/', base_pages_view.about, name="about_us"),
    path('dashboard/', base_pages_view.dashboard, name="dashboard"),
    path('my_posts/', base_pages_view.my_posts, name="my_posts"),
    path('my_jobs/', base_pages_view.my_jobs, name="my_jobs"),
    path('my_profile/', base_pages_view.my_profile, name="my_profile"),
    path('faq/', base_pages_view.faq, name="faq"),
    path('contact_us/', base_pages_view.contact_us, name="contact_us"),
    path('search/', base_pages_view.search_view, name="search_view"),
    path('privacy_page/', base_pages_view.privacy_page, name="privacy_page"),
    path('jobs/', base_pages_view.job_page_coming_soon, name="job_page_coming_soon"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', include("robots.urls", namespace="")),
    url(r'^robots\.txt', include('robots.urls')),

    # Advertorials
    path('ads.txt/', base_pages_view.ads, name="ads"),

    # 404 and 500 Error Pages
    path('404_test/', base_pages_view.handler404, name="404_test"),
    path('500_test/', base_pages_view.handler500, name="500_test"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('edit_profile/', views.update_profile, name="update_profile"),


]

templates/category_pages/categories_detail.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Kategoriler - {{ block.super }}{% endblock %}

{% block body %}

    <section class="s-content">

        <div class="row masonry-wrap">
            <div class="masonry">
                <div class="grid-sizer"></div>
                {% if category_list %}
                    {% for post in category_list %}
                        <article class="masonry__brick entry format-standard" data-aos="fade-up">

                            <div class="entry__thumb">
                                <a href="{% url 'posts:detail' slug=post.slug %}" class="entry__thumb-link">
                                    <img src="images/thumbs/masonry/tulips-400.jpg"
                                         srcset="images/thumbs/masonry/tulips-400.jpg 1x, images/thumbs/masonry/tulips-800.jpg 2x"
                                         alt="">
                                </a>
                            </div>

                            <div class="entry__text">
                                <div class="entry__header">


                                    <div class="entry__date" style="text-align: right">
                                        <a href="{% url 'posts:detail' slug=post.slug %}">{{ post.created_date|date:"F d, Y" }}</a>

                                    </div>
                                    <h1 class="entry__title"><a
                                            href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a>
                                    </h1>

                                </div>

                                <div class="entry__excerpt">
                                    <p>
                                        {{ post.description|striptags|truncatewords:28|safe }}
                                    </p>
                                </div>


                                <div class="entry__content">
                                    <a href="{% url 'user:profile' slug=post.author %}" class="entry__profile-pic">
                                        <img class="avatar" src="{{ post.author.profile.avatar.url }}" alt="">
                                    </a>

                                    <div class="entry__date">
                                        <a href="{% url 'user:profile' slug=post.author %}">&nbsp{{ post.author }}</a>

                                    </div>

                                    <hr>


                                    <div class="entry__meta">
                            <span class="entry__meta-links">
                                {% for tag in post.tag.all|slice:":3" %}
                                    <a href="{% url 'categories:categories' slug=tag.slug %}">


                                   <img src="{{ tag.sub_category_image.url }}" alt="" title="{{ tag }}"
                                         style="width: 10%">
                                </a>
                                {% endfor %}
                            </span>
                                    </div>

                                </div>
                            </div>

                        </article> <!-- end article -->
                    {% endfor %}
                {% else %}

                    </div> <!-- end masonry -->
                    <h3 class="text-center">Bu kategoride herhangi bir post bulunmuyor..
                        <a href="{% url 'posts:add_post' %}">Hemen oluşturun :)</a>
                    </h3>

                {% endif %}
        </div> <!-- end masonry-wrap -->


    </section> <!-- s-content -->

{% endblock body %}

templates/category_pages/subcategories_detail.html
{% extends "base/layout.html" %}
{% load static %}
{% include 'base/components/scripts.html' %}
{% block title %}Alt Kategoriler - {{ block.super }}{% endblock %}

{% block body %}

    <section class="s-content">

        <div class="row masonry-wrap">
            <div class="masonry">
                <div class="grid-sizer"></div>
                {% if subcategory_list %}
                    {% for post in subcategory_list %}
                        <article class="masonry__brick entry format-standard" data-aos="fade-up">

                            <div class="entry__thumb">
                                <a href="{% url 'posts:detail' slug=post.slug %}" class="entry__thumb-link">
                                    <img src="images/thumbs/masonry/tulips-400.jpg"
                                         srcset="images/thumbs/masonry/tulips-400.jpg 1x, images/thumbs/masonry/tulips-800.jpg 2x"
                                         alt="">
                                </a>
                            </div>

                            <div class="entry__text">
                                <div class="entry__header">


                                    <div class="entry__date" style="text-align: right">
                                        <a href="{% url 'posts:detail' slug=post.slug %}">{{ post.created_date|date:"F d, Y" }}</a>

                                    </div>
                                    <h1 class="entry__title"><a
                                            href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a>
                                    </h1>

                                </div>

                                <div class="entry__excerpt">
                                    <p>
                                        {{ post.description|striptags|truncatewords:28|safe }}
                                    </p>
                                </div>


                                <div class="entry__content">
                                    <a href="{% url 'user:profile' slug=post.author %}" class="entry__profile-pic">
                                        <img class="avatar" src="{{ post.author.profile.avatar.url }}" alt="">
                                    </a>

                                    <div class="entry__date">
                                        <a href="{% url 'user:profile' slug=post.author %}">&nbsp{{ post.author }}</a>

                                    </div>

                                    <hr>


                                    <div class="entry__meta">
                            <span class="entry__meta-links">
                                {% for tag in post.tag.all|slice:":3" %}
                                    <a href="{% url 'categories:categories' slug=tag.slug %}">


                                   <img src="{{ tag.sub_category_image.url }}" alt="" title="{{ tag }}"
                                         style="width: 10%">
                                </a>
                                {% endfor %}
                            </span>
                                    </div>

                                </div>
                            </div>

                        </article> <!-- end article -->
                    {% endfor %}
                {% else %}

                    </div> <!-- end masonry -->
                    <h3 class="text-center">Bu kategoride herhangi bir post bulunmuyor..
                        <a href="{% url 'posts:add_post' %}">Hemen oluşturun :)</a>
                    </h3>

                {% endif %}
        </div> <!-- end masonry-wrap -->


    </section> <!-- s-content -->

{% endblock body %}